version: '3.8'

services:
  trino:
    image: trinodb/trino:422
    container_name: trino
    ports:
      - "8080:8080"
    volumes:
      - ./etc:/etc/trino
      - ./credentials:/credentials
    environment:
      - NODE_ID=trino-coordinator
      - SHEETS_METADATA_ID=1eXhYmSob8rSFWDtG7F_j6pzxNws22Err9LCoHLWsXAw#metadata
      # Service account path is configured in sheets.properties
    networks:
      - trino-network

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - trino-network
    restart: unless-stopped

networks:
  trino-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local 